/* 
 * Tripwire Enterprise TE REST API User Guide & Reference
 *
 * The TE REST API allows automation of many aspects of Tripwire Enterprise
 *
 * OpenAPI spec version: 1.13.0.bmaster.r20180119190259-8b60eaa.b1753
 * Contact: support@tripwire.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NodesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class NodesApiTests
    {
        private NodesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new NodesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NodesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' NodesApi
            //Assert.IsInstanceOfType(typeof(NodesApi), instance, "instance is a NodesApi");
        }

        
        /// <summary>
        /// Test CreateCustomPropertyType
        /// </summary>
        [Test]
        public void CreateCustomPropertyTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomPropertyType body = null;
            //var response = instance.CreateCustomPropertyType(body);
            //Assert.IsInstanceOf<CustomPropertyType> (response, "response is CustomPropertyType");
        }
        
        /// <summary>
        /// Test CreateNode
        /// </summary>
        [Test]
        public void CreateNodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Node body = null;
            //var response = instance.CreateNode(body);
            //Assert.IsInstanceOf<Node> (response, "response is Node");
        }
        
        /// <summary>
        /// Test CreateNodeAcl
        /// </summary>
        [Test]
        public void CreateNodeAclTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkNodeId = null;
            //Object body = null;
            //var response = instance.CreateNodeAcl(rkNodeId, body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test DeleteCustomPropertyType
        /// </summary>
        [Test]
        public void DeleteCustomPropertyTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkCustomPropertyTypeId = null;
            //instance.DeleteCustomPropertyType(rkCustomPropertyTypeId);
            
        }
        
        /// <summary>
        /// Test DeleteNode
        /// </summary>
        [Test]
        public void DeleteNodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkNodeId = null;
            //instance.DeleteNode(rkNodeId);
            
        }
        
        /// <summary>
        /// Test DeleteNodeCustomProperty
        /// </summary>
        [Test]
        public void DeleteNodeCustomPropertyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkNodeId = null;
            //string propertyName = null;
            //instance.DeleteNodeCustomProperty(rkNodeId, propertyName);
            
        }
        
        /// <summary>
        /// Test GetCustomProperties
        /// </summary>
        [Test]
        public void GetCustomPropertiesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkNodeId = null;
            //var response = instance.GetCustomProperties(rkNodeId);
            //Assert.IsInstanceOf<CustomProperties> (response, "response is CustomProperties");
        }
        
        /// <summary>
        /// Test GetCustomPropertyTypeById
        /// </summary>
        [Test]
        public void GetCustomPropertyTypeByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkCustomPropertyTypeId = null;
            //var response = instance.GetCustomPropertyTypeById(rkCustomPropertyTypeId);
            //Assert.IsInstanceOf<CustomPropertyType> (response, "response is CustomPropertyType");
        }
        
        /// <summary>
        /// Test GetCustomPropertyTypes
        /// </summary>
        [Test]
        public void GetCustomPropertyTypesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? allowMultilineValues = null;
            //List<string> availableValues = null;
            //List<string> defaultValue = null;
            //List<string> description = null;
            //List<string> id = null;
            //bool? inheritDefault = null;
            //List<string> maxCharacters = null;
            //List<string> maxValue = null;
            //List<string> minValue = null;
            //List<string> name = null;
            //List<string> subDescription = null;
            //List<string> textEditorWidth = null;
            //List<string> type = null;
            //var response = instance.GetCustomPropertyTypes(allowMultilineValues, availableValues, defaultValue, description, id, inheritDefault, maxCharacters, maxValue, minValue, name, subDescription, textEditorWidth, type);
            //Assert.IsInstanceOf<CustomPropertyType> (response, "response is CustomPropertyType");
        }
        
        /// <summary>
        /// Test GetNodeAcl
        /// </summary>
        [Test]
        public void GetNodeAclTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkNodeId = null;
            //var response = instance.GetNodeAcl(rkNodeId);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test GetNodeById
        /// </summary>
        [Test]
        public void GetNodeByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkNodeId = null;
            //var response = instance.GetNodeById(rkNodeId);
            //Assert.IsInstanceOf<Node> (response, "response is Node");
        }
        
        /// <summary>
        /// Test GetNodeParentGroups
        /// </summary>
        [Test]
        public void GetNodeParentGroupsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkNodeId = null;
            //var response = instance.GetNodeParentGroups(rkNodeId);
            //Assert.IsInstanceOf<NodeGroupPath> (response, "response is NodeGroupPath");
        }
        
        /// <summary>
        /// Test GetNodes
        /// </summary>
        [Test]
        public void GetNodesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> agentVersion = null;
            //bool? auditEnabled = null;
            //List<string> commonAgentCapabilities = null;
            //List<string> commonAgentOsName = null;
            //List<string> commonAgentOsVersion = null;
            //List<string> commonAgentUuid = null;
            //List<string> commonAgentVersion = null;
            //List<string> customProperty = null;
            //List<string> description = null;
            //List<string> elementCount = null;
            //bool? eventGeneratorEnabled = null;
            //bool? eventGeneratorInstalled = null;
            //bool? hasFailures = null;
            //List<string> icName = null;
            //List<string> id = null;
            //List<string> importedTime = null;
            //string importedTimeRange = null;
            //List<string> ipAddress = null;
            //bool? isDisabled = null;
            //bool? isSocksProxy = null;
            //bool? isSSLSupported = null;
            //List<string> lastCheck = null;
            //List<string> lastRegistration = null;
            //List<string> licensedFeature = null;
            //List<string> macAddress = null;
            //List<string> make = null;
            //List<string> maxSeverity = null;
            //List<string> model = null;
            //List<string> modifiedTime = null;
            //List<string> name = null;
            //List<string> oid = null;
            //string pageLimit = null;
            //string pageStart = null;
            //List<string> proxyHost = null;
            //List<string> proxyPort = null;
            //bool? realTimeEnabled = null;
            //List<string> rmiHost = null;
            //List<string> rmiPort = null;
            //List<string> subDescription = null;
            //List<string> subName = null;
            //List<string> tag = null;
            //List<string> trackingId = null;
            //List<string> type = null;
            //bool? usingSSL = null;
            //List<string> version = null;
            //var response = instance.GetNodes(agentVersion, auditEnabled, commonAgentCapabilities, commonAgentOsName, commonAgentOsVersion, commonAgentUuid, commonAgentVersion, customProperty, description, elementCount, eventGeneratorEnabled, eventGeneratorInstalled, hasFailures, icName, id, importedTime, importedTimeRange, ipAddress, isDisabled, isSocksProxy, isSSLSupported, lastCheck, lastRegistration, licensedFeature, macAddress, make, maxSeverity, model, modifiedTime, name, oid, pageLimit, pageStart, proxyHost, proxyPort, realTimeEnabled, rmiHost, rmiPort, subDescription, subName, tag, trackingId, type, usingSSL, version);
            //Assert.IsInstanceOf<Node> (response, "response is Node");
        }
        
        /// <summary>
        /// Test GetRuleRunRequestById
        /// </summary>
        [Test]
        public void GetRuleRunRequestByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string requestId = null;
            //var response = instance.GetRuleRunRequestById(requestId);
            //Assert.IsInstanceOf<RuleRunRequestCommand> (response, "response is RuleRunRequestCommand");
        }
        
        /// <summary>
        /// Test RestartNodes
        /// </summary>
        [Test]
        public void RestartNodesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NodeRestart body = null;
            //var response = instance.RestartNodes(body);
            //Assert.IsInstanceOf<NodeRestartResult> (response, "response is NodeRestartResult");
        }
        
        /// <summary>
        /// Test RetireNode
        /// </summary>
        [Test]
        public void RetireNodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkNodeId = null;
            //instance.RetireNode(rkNodeId);
            
        }
        
        /// <summary>
        /// Test RuleRunRequest
        /// </summary>
        [Test]
        public void RuleRunRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RuleRunRequestCommand body = null;
            //var response = instance.RuleRunRequest(body);
            //Assert.IsInstanceOf<RuleRunRequestCommand> (response, "response is RuleRunRequestCommand");
        }
        
        /// <summary>
        /// Test SetNodeCustomProperty
        /// </summary>
        [Test]
        public void SetNodeCustomPropertyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkNodeId = null;
            //string propertyName = null;
            //PropertyValue body = null;
            //instance.SetNodeCustomProperty(rkNodeId, propertyName, body);
            
        }
        
        /// <summary>
        /// Test UnregisterCommonAgent
        /// </summary>
        [Test]
        public void UnregisterCommonAgentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkNodeId = null;
            //instance.UnregisterCommonAgent(rkNodeId);
            
        }
        
        /// <summary>
        /// Test UpdateCustomPropertyType
        /// </summary>
        [Test]
        public void UpdateCustomPropertyTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomPropertyType body = null;
            //string rkCustomPropertyTypeId = null;
            //var response = instance.UpdateCustomPropertyType(body, rkCustomPropertyTypeId);
            //Assert.IsInstanceOf<CustomPropertyType> (response, "response is CustomPropertyType");
        }
        
        /// <summary>
        /// Test UpdateNode
        /// </summary>
        [Test]
        public void UpdateNodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkNodeId = null;
            //Node body = null;
            //var response = instance.UpdateNode(rkNodeId, body);
            //Assert.IsInstanceOf<Node> (response, "response is Node");
        }
        
    }

}
