/* 
 * Tripwire Enterprise TE REST API User Guide & Reference
 *
 * The TE REST API allows automation of many aspects of Tripwire Enterprise
 *
 * OpenAPI spec version: 1.13.0.bmaster.r20180119190259-8b60eaa.b1753
 * Contact: support@tripwire.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TaskgroupsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TaskgroupsApiTests
    {
        private TaskgroupsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TaskgroupsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskgroupsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TaskgroupsApi
            //Assert.IsInstanceOfType(typeof(TaskgroupsApi), instance, "instance is a TaskgroupsApi");
        }

        
        /// <summary>
        /// Test AssociateTaskGroupableToTaskGroup
        /// </summary>
        [Test]
        public void AssociateTaskGroupableToTaskGroupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkTaskGroupId = null;
            //string rkTaskGroupableId = null;
            //instance.AssociateTaskGroupableToTaskGroup(rkTaskGroupId, rkTaskGroupableId);
            
        }
        
        /// <summary>
        /// Test CreateTaskGroup
        /// </summary>
        [Test]
        public void CreateTaskGroupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TaskGroup body = null;
            //var response = instance.CreateTaskGroup(body);
            //Assert.IsInstanceOf<TaskGroup> (response, "response is TaskGroup");
        }
        
        /// <summary>
        /// Test DeleteTaskGroup
        /// </summary>
        [Test]
        public void DeleteTaskGroupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkTaskGroupId = null;
            //instance.DeleteTaskGroup(rkTaskGroupId);
            
        }
        
        /// <summary>
        /// Test DisassociateTaskGroupableFromTaskGroup
        /// </summary>
        [Test]
        public void DisassociateTaskGroupableFromTaskGroupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkTaskGroupId = null;
            //string rkTaskGroupableId = null;
            //instance.DisassociateTaskGroupableFromTaskGroup(rkTaskGroupId, rkTaskGroupableId);
            
        }
        
        /// <summary>
        /// Test GetRootTaskGroup
        /// </summary>
        [Test]
        public void GetRootTaskGroupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetRootTaskGroup();
            //Assert.IsInstanceOf<TaskGroup> (response, "response is TaskGroup");
        }
        
        /// <summary>
        /// Test GetTaskGroupById
        /// </summary>
        [Test]
        public void GetTaskGroupByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkTaskGroupId = null;
            //var response = instance.GetTaskGroupById(rkTaskGroupId);
            //Assert.IsInstanceOf<TaskGroup> (response, "response is TaskGroup");
        }
        
        /// <summary>
        /// Test GetTaskGroupChildren
        /// </summary>
        [Test]
        public void GetTaskGroupChildrenTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkTaskGroupId = null;
            //var response = instance.GetTaskGroupChildren(rkTaskGroupId);
            //Assert.IsInstanceOf<TaskGroupChild> (response, "response is TaskGroupChild");
        }
        
        /// <summary>
        /// Test GetTaskGroups
        /// </summary>
        [Test]
        public void GetTaskGroupsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> description = null;
            //List<string> id = null;
            //List<string> importedTime = null;
            //List<string> modifiedTime = null;
            //List<string> name = null;
            //string pageLimit = null;
            //string pageStart = null;
            //List<string> subDescription = null;
            //List<string> trackingId = null;
            //var response = instance.GetTaskGroups(description, id, importedTime, modifiedTime, name, pageLimit, pageStart, subDescription, trackingId);
            //Assert.IsInstanceOf<TaskGroup> (response, "response is TaskGroup");
        }
        
    }

}
