/* 
 * Tripwire Enterprise TE REST API User Guide & Reference
 *
 * The TE REST API allows automation of many aspects of Tripwire Enterprise
 *
 * OpenAPI spec version: 1.13.0.bmaster.r20180119190259-8b60eaa.b1753
 * Contact: support@tripwire.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TasksApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TasksApiTests
    {
        private TasksApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TasksApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TasksApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TasksApi
            //Assert.IsInstanceOfType(typeof(TasksApi), instance, "instance is a TasksApi");
        }

        
        /// <summary>
        /// Test CreateExecuteTaskRequest
        /// </summary>
        [Test]
        public void CreateExecuteTaskRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ExecuteTaskRequestCommand body = null;
            //var response = instance.CreateExecuteTaskRequest(body);
            //Assert.IsInstanceOf<ExecuteTaskRequestCommand> (response, "response is ExecuteTaskRequestCommand");
        }
        
        /// <summary>
        /// Test CreateTask
        /// </summary>
        [Test]
        public void CreateTaskTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Task body = null;
            //var response = instance.CreateTask(body);
            //Assert.IsInstanceOf<Task> (response, "response is Task");
        }
        
        /// <summary>
        /// Test DeleteTask
        /// </summary>
        [Test]
        public void DeleteTaskTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkTaskId = null;
            //instance.DeleteTask(rkTaskId);
            
        }
        
        /// <summary>
        /// Test GetExecutionTaskRequestById
        /// </summary>
        [Test]
        public void GetExecutionTaskRequestByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string requestId = null;
            //var response = instance.GetExecutionTaskRequestById(requestId);
            //Assert.IsInstanceOf<ExecuteTaskRequestCommand> (response, "response is ExecuteTaskRequestCommand");
        }
        
        /// <summary>
        /// Test GetNodeStatus
        /// </summary>
        [Test]
        public void GetNodeStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkTaskId = null;
            //var response = instance.GetNodeStatus(rkTaskId);
            //Assert.IsInstanceOf<NodeStatus> (response, "response is NodeStatus");
        }
        
        /// <summary>
        /// Test GetRunContextNodeRules
        /// </summary>
        [Test]
        public void GetRunContextNodeRulesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> contextId = null;
            //List<string> endTime = null;
            //string endTimeRange = null;
            //string hasErrors = null;
            //string hasTimeout = null;
            //List<string> lastUpdated = null;
            //string lastUpdatedRange = null;
            //List<string> nodeId = null;
            //string pageLimit = null;
            //string pageStart = null;
            //string receivedEnd = null;
            //List<string> ruleId = null;
            //List<string> runType = null;
            //List<string> startTime = null;
            //string startTimeRange = null;
            //string wasCancelled = null;
            //var response = instance.GetRunContextNodeRules(contextId, endTime, endTimeRange, hasErrors, hasTimeout, lastUpdated, lastUpdatedRange, nodeId, pageLimit, pageStart, receivedEnd, ruleId, runType, startTime, startTimeRange, wasCancelled);
            //Assert.IsInstanceOf<RunContextNodeRule> (response, "response is RunContextNodeRule");
        }
        
        /// <summary>
        /// Test GetRunContextNodeRulesLatest
        /// </summary>
        [Test]
        public void GetRunContextNodeRulesLatestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> contextId = null;
            //List<string> endTime = null;
            //string endTimeRange = null;
            //string hasErrors = null;
            //string hasTimeout = null;
            //List<string> lastUpdated = null;
            //string lastUpdatedRange = null;
            //List<string> nodeId = null;
            //string pageLimit = null;
            //string pageStart = null;
            //string receivedEnd = null;
            //List<string> ruleId = null;
            //List<string> runType = null;
            //List<string> startTime = null;
            //string startTimeRange = null;
            //string wasCancelled = null;
            //var response = instance.GetRunContextNodeRulesLatest(contextId, endTime, endTimeRange, hasErrors, hasTimeout, lastUpdated, lastUpdatedRange, nodeId, pageLimit, pageStart, receivedEnd, ruleId, runType, startTime, startTimeRange, wasCancelled);
            //Assert.IsInstanceOf<RunContextNodeRule> (response, "response is RunContextNodeRule");
        }
        
        /// <summary>
        /// Test GetRunContexts
        /// </summary>
        [Test]
        public void GetRunContextsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> endTime = null;
            //string endTimeRange = null;
            //string hasErrors = null;
            //List<string> id = null;
            //string pageLimit = null;
            //string previousId = null;
            //List<string> runType = null;
            //List<string> startTime = null;
            //string startTimeRange = null;
            //List<string> stopType = null;
            //List<string> taskId = null;
            //var response = instance.GetRunContexts(endTime, endTimeRange, hasErrors, id, pageLimit, previousId, runType, startTime, startTimeRange, stopType, taskId);
            //Assert.IsInstanceOf<RunContext> (response, "response is RunContext");
        }
        
        /// <summary>
        /// Test GetRunContextsLatest
        /// </summary>
        [Test]
        public void GetRunContextsLatestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> endTime = null;
            //string endTimeRange = null;
            //string hasErrors = null;
            //List<string> id = null;
            //string pageLimit = null;
            //string previousId = null;
            //List<string> runType = null;
            //List<string> startTime = null;
            //string startTimeRange = null;
            //List<string> stopType = null;
            //List<string> taskId = null;
            //var response = instance.GetRunContextsLatest(endTime, endTimeRange, hasErrors, id, pageLimit, previousId, runType, startTime, startTimeRange, stopType, taskId);
            //Assert.IsInstanceOf<RunContext> (response, "response is RunContext");
        }
        
        /// <summary>
        /// Test GetTargetableNodes
        /// </summary>
        [Test]
        public void GetTargetableNodesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkTaskId = null;
            //var response = instance.GetTargetableNodes(rkTaskId);
            //Assert.IsInstanceOf<Node> (response, "response is Node");
        }
        
        /// <summary>
        /// Test GetTaskById
        /// </summary>
        [Test]
        public void GetTaskByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkTaskId = null;
            //var response = instance.GetTaskById(rkTaskId);
            //Assert.IsInstanceOf<Task> (response, "response is Task");
        }
        
        /// <summary>
        /// Test GetTasks
        /// </summary>
        [Test]
        public void GetTasksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> actionIds = null;
            //List<string> additionalEmailAddresses = null;
            //bool? archiveAuditEvents = null;
            //List<string> archiveLogsExceeding = null;
            //List<string> archiveLogsOlderThan = null;
            //bool? archiveReports = null;
            //List<string> compactVersionsExceeding = null;
            //List<string> compactVersionsOlderThan = null;
            //List<string> description = null;
            //List<string> emailServer = null;
            //bool? enabled = null;
            //List<string> id = null;
            //bool? ignoreEmptyReports = null;
            //List<string> lastDuration = null;
            //List<string> lastStart = null;
            //List<string> name = null;
            //bool? newBaselinesOnly = null;
            //List<string> nextStart = null;
            //List<string> nodeId = null;
            //string pageLimit = null;
            //string pageStart = null;
            //List<string> reportFormat = null;
            //List<string> reportId = null;
            //List<string> reportUserIds = null;
            //List<string> ruleId = null;
            //List<string> status = null;
            //List<string> subDescription = null;
            //List<string> timeout = null;
            //List<string> type = null;
            //List<string> userId = null;
            //var response = instance.GetTasks(actionIds, additionalEmailAddresses, archiveAuditEvents, archiveLogsExceeding, archiveLogsOlderThan, archiveReports, compactVersionsExceeding, compactVersionsOlderThan, description, emailServer, enabled, id, ignoreEmptyReports, lastDuration, lastStart, name, newBaselinesOnly, nextStart, nodeId, pageLimit, pageStart, reportFormat, reportId, reportUserIds, ruleId, status, subDescription, timeout, type, userId);
            //Assert.IsInstanceOf<Task> (response, "response is Task");
        }
        
        /// <summary>
        /// Test UpdateTask
        /// </summary>
        [Test]
        public void UpdateTaskTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkTaskId = null;
            //Task task = null;
            //var response = instance.UpdateTask(rkTaskId, task);
            //Assert.IsInstanceOf<Task> (response, "response is Task");
        }
        
    }

}
