/* 
 * Tripwire Enterprise TE REST API User Guide & Reference
 *
 * The TE REST API allows automation of many aspects of Tripwire Enterprise
 *
 * OpenAPI spec version: 1.12.1.bmaster.r20170922182356-4e84151.b1741
 * Contact: support@tripwire.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WaiversApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class WaiversApiTests
    {
        private WaiversApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WaiversApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WaiversApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' WaiversApi
            //Assert.IsInstanceOfType(typeof(WaiversApi), instance, "instance is a WaiversApi");
        }

        
        /// <summary>
        /// Test DeleteWaiver
        /// </summary>
        [Test]
        public void DeleteWaiverTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkWaiverId = null;
            //instance.DeleteWaiver(rkWaiverId);
            
        }
        
        /// <summary>
        /// Test GetWaiverById
        /// </summary>
        [Test]
        public void GetWaiverByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rkWaiverId = null;
            //var response = instance.GetWaiverById(rkWaiverId);
            //Assert.IsInstanceOf<Waiver> (response, "response is Waiver");
        }
        
        /// <summary>
        /// Test GetWaivers
        /// </summary>
        [Test]
        public void GetWaiversTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string pageLimit = null;
            //string pageStart = null;
            //List<string> id = null;
            //List<string> name = null;
            //List<string> description = null;
            //List<string> subDescription = null;
            //List<string> policyId = null;
            //List<string> policyName = null;
            //List<string> startTime = null;
            //List<string> expiration = null;
            //List<string> grantedBy = null;
            //List<string> responsible = null;
            //bool? closed = null;
            //var response = instance.GetWaivers(pageLimit, pageStart, id, name, description, subDescription, policyId, policyName, startTime, expiration, grantedBy, responsible, closed);
            //Assert.IsInstanceOf<List<Waiver>> (response, "response is List<Waiver>");
        }
        
    }

}
