/* 
 * Tripwire Enterprise TE REST API User Guide & Reference
 *
 * The TE REST API allows automation of many aspects of Tripwire Enterprise
 *
 * OpenAPI spec version: 1.12.1.bmaster.r20170922182356-4e84151.b1741
 * Contact: support@tripwire.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// A collection of policies to run and a collection of nodes the run is restricted to
    /// </summary>
    [DataContract]
    public partial class PolicyRun :  IEquatable<PolicyRun>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PolicyRun" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PolicyRun() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PolicyRun" /> class.
        /// </summary>
        /// <param name="policies">The collection of Readable-Keys identifying the policies to run (required).</param>
        /// <param name="nodes">The collection of node Readable-keys the run is restricted to.</param>
        public PolicyRun(List<string> policies = default(List<string>), List<string> nodes = default(List<string>))
        {
            // to ensure "policies" is required (not null)
            if (policies == null)
            {
                throw new InvalidDataException("policies is a required property for PolicyRun and cannot be null");
            }
            else
            {
                this.Policies = policies;
            }
            this.Nodes = nodes;
        }
        
        /// <summary>
        /// The collection of Readable-Keys identifying the policies to run
        /// </summary>
        /// <value>The collection of Readable-Keys identifying the policies to run</value>
        [DataMember(Name="policies", EmitDefaultValue=false)]
        public List<string> Policies { get; set; }

        /// <summary>
        /// The collection of node Readable-keys the run is restricted to
        /// </summary>
        /// <value>The collection of node Readable-keys the run is restricted to</value>
        [DataMember(Name="nodes", EmitDefaultValue=false)]
        public List<string> Nodes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PolicyRun {\n");
            sb.Append("  Policies: ").Append(Policies).Append("\n");
            sb.Append("  Nodes: ").Append(Nodes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PolicyRun);
        }

        /// <summary>
        /// Returns true if PolicyRun instances are equal
        /// </summary>
        /// <param name="input">Instance of PolicyRun to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PolicyRun input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Policies == input.Policies ||
                    this.Policies != null &&
                    this.Policies.SequenceEqual(input.Policies)
                ) && 
                (
                    this.Nodes == input.Nodes ||
                    this.Nodes != null &&
                    this.Nodes.SequenceEqual(input.Nodes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Policies != null)
                    hashCode = hashCode * 59 + this.Policies.GetHashCode();
                if (this.Nodes != null)
                    hashCode = hashCode * 59 + this.Nodes.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
