/* 
 * Tripwire Enterprise TE REST API User Guide & Reference
 *
 * The TE REST API allows automation of many aspects of Tripwire Enterprise
 *
 * OpenAPI spec version: 1.13.0.bmaster.r20180119190259-8b60eaa.b1753
 * Contact: support@tripwire.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Represents the lack of a result for a node in scope for a policy test
    /// </summary>
    [DataContract]
    public partial class UnknownPolicyTestResult :  IEquatable<UnknownPolicyTestResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UnknownPolicyTestResult" /> class.
        /// </summary>
        /// <param name="nodeId">Id of the node that is missing results.</param>
        /// <param name="policyId">Id of the policy that is missing results.</param>
        /// <param name="policyTestId">Id of the policy test.</param>
        public UnknownPolicyTestResult(string nodeId = default(string), string policyId = default(string), string policyTestId = default(string))
        {
            this.NodeId = nodeId;
            this.PolicyId = policyId;
            this.PolicyTestId = policyTestId;
        }
        
        /// <summary>
        /// Id of the node that is missing results
        /// </summary>
        /// <value>Id of the node that is missing results</value>
        [DataMember(Name="nodeId", EmitDefaultValue=false)]
        public string NodeId { get; set; }

        /// <summary>
        /// Id of the policy that is missing results
        /// </summary>
        /// <value>Id of the policy that is missing results</value>
        [DataMember(Name="policyId", EmitDefaultValue=false)]
        public string PolicyId { get; set; }

        /// <summary>
        /// Id of the policy test
        /// </summary>
        /// <value>Id of the policy test</value>
        [DataMember(Name="policyTestId", EmitDefaultValue=false)]
        public string PolicyTestId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UnknownPolicyTestResult {\n");
            sb.Append("  NodeId: ").Append(NodeId).Append("\n");
            sb.Append("  PolicyId: ").Append(PolicyId).Append("\n");
            sb.Append("  PolicyTestId: ").Append(PolicyTestId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UnknownPolicyTestResult);
        }

        /// <summary>
        /// Returns true if UnknownPolicyTestResult instances are equal
        /// </summary>
        /// <param name="input">Instance of UnknownPolicyTestResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UnknownPolicyTestResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.NodeId == input.NodeId ||
                    (this.NodeId != null &&
                    this.NodeId.Equals(input.NodeId))
                ) && 
                (
                    this.PolicyId == input.PolicyId ||
                    (this.PolicyId != null &&
                    this.PolicyId.Equals(input.PolicyId))
                ) && 
                (
                    this.PolicyTestId == input.PolicyTestId ||
                    (this.PolicyTestId != null &&
                    this.PolicyTestId.Equals(input.PolicyTestId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NodeId != null)
                    hashCode = hashCode * 59 + this.NodeId.GetHashCode();
                if (this.PolicyId != null)
                    hashCode = hashCode * 59 + this.PolicyId.GetHashCode();
                if (this.PolicyTestId != null)
                    hashCode = hashCode * 59 + this.PolicyTestId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
