/* 
 * Tripwire Enterprise TE REST API User Guide & Reference
 *
 * The TE REST API allows automation of many aspects of Tripwire Enterprise
 *
 * OpenAPI spec version: 1.12.1.bmaster.r20170922182356-4e84151.b1741
 * Contact: support@tripwire.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RemediationData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RemediationDataTests
    {
        // TODO uncomment below to declare an instance variable for RemediationData
        //private RemediationData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RemediationData
            //instance = new RemediationData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RemediationData
        /// </summary>
        [Test]
        public void RemediationDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RemediationData
            //Assert.IsInstanceOfType<RemediationData> (instance, "variable 'instance' is a RemediationData");
        }


        /// <summary>
        /// Test the property 'PolicyTestResultIds'
        /// </summary>
        [Test]
        public void PolicyTestResultIdsTest()
        {
            // TODO unit test for the property 'PolicyTestResultIds'
        }
        /// <summary>
        /// Test the property 'ApprovalId'
        /// </summary>
        [Test]
        public void ApprovalIdTest()
        {
            // TODO unit test for the property 'ApprovalId'
        }
        /// <summary>
        /// Test the property 'ApprovalComment'
        /// </summary>
        [Test]
        public void ApprovalCommentTest()
        {
            // TODO unit test for the property 'ApprovalComment'
        }
        /// <summary>
        /// Test the property 'DeleteWhenComplete'
        /// </summary>
        [Test]
        public void DeleteWhenCompleteTest()
        {
            // TODO unit test for the property 'DeleteWhenComplete'
        }

    }

}
