/* 
 * Tripwire Enterprise TE REST API User Guide & Reference
 *
 * The TE REST API allows automation of many aspects of Tripwire Enterprise
 *
 * OpenAPI spec version: 1.12.1.bmaster.r20170922182356-4e84151.b1741
 * Contact: support@tripwire.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RuleRunRequestCommand
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RuleRunRequestCommandTests
    {
        // TODO uncomment below to declare an instance variable for RuleRunRequestCommand
        //private RuleRunRequestCommand instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RuleRunRequestCommand
            //instance = new RuleRunRequestCommand();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RuleRunRequestCommand
        /// </summary>
        [Test]
        public void RuleRunRequestCommandInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RuleRunRequestCommand
            //Assert.IsInstanceOfType<RuleRunRequestCommand> (instance, "variable 'instance' is a RuleRunRequestCommand");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'RequestData'
        /// </summary>
        [Test]
        public void RequestDataTest()
        {
            // TODO unit test for the property 'RequestData'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusMessage'
        /// </summary>
        [Test]
        public void StatusMessageTest()
        {
            // TODO unit test for the property 'StatusMessage'
        }
        /// <summary>
        /// Test the property 'CreationTime'
        /// </summary>
        [Test]
        public void CreationTimeTest()
        {
            // TODO unit test for the property 'CreationTime'
        }
        /// <summary>
        /// Test the property 'CompletionTime'
        /// </summary>
        [Test]
        public void CompletionTimeTest()
        {
            // TODO unit test for the property 'CompletionTime'
        }

    }

}
