/* 
 * Tripwire Enterprise TE REST API User Guide & Reference
 *
 * The TE REST API allows automation of many aspects of Tripwire Enterprise
 *
 * OpenAPI spec version: 1.13.0.bmaster.r20180119190259-8b60eaa.b1753
 * Contact: support@tripwire.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWaiversApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Delete a waiver (since 1.11)
        /// </summary>
        /// <remarks>
        /// Removes a waiver
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rkWaiverId">Id of the waiver</param>
        /// <returns></returns>
        void DeleteWaiver (string rkWaiverId);

        /// <summary>
        /// Delete a waiver (since 1.11)
        /// </summary>
        /// <remarks>
        /// Removes a waiver
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rkWaiverId">Id of the waiver</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteWaiverWithHttpInfo (string rkWaiverId);
        /// <summary>
        /// Get waiver details by ID. (since 1.5)
        /// </summary>
        /// <remarks>
        /// Returns the details of an individual waiver.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rkWaiverId">ID of Waiver to fetch</param>
        /// <returns>Waiver</returns>
        Waiver GetWaiverById (string rkWaiverId);

        /// <summary>
        /// Get waiver details by ID. (since 1.5)
        /// </summary>
        /// <remarks>
        /// Returns the details of an individual waiver.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rkWaiverId">ID of Waiver to fetch</param>
        /// <returns>ApiResponse of Waiver</returns>
        ApiResponse<Waiver> GetWaiverByIdWithHttpInfo (string rkWaiverId);
        /// <summary>
        /// Search waivers (since 1.5)
        /// </summary>
        /// <remarks>
        /// Returns a list of all waivers or only those waivers that match the provided filter criteria.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="closed">Closed condition of waivers to fetch. (optional)</param>
        /// <param name="description">Descriptions of waivers to fetch. (optional)</param>
        /// <param name="expiration">Expiration times of waivers to fetch. (optional)</param>
        /// <param name="grantedBy">Granted by waivers to fetch. (optional)</param>
        /// <param name="id">IDs of waivers to fetch. (optional)</param>
        /// <param name="name">Names of waivers to fetch. (optional)</param>
        /// <param name="pageLimit">Page limit for paging support (optional)</param>
        /// <param name="pageStart">Page start for paging support (optional)</param>
        /// <param name="policyId">Policy IDs of waivers to fetch. (optional)</param>
        /// <param name="policyName">Policy names of waivers to fetch. (optional)</param>
        /// <param name="responsible">Responsibles of waivers to fetch. (optional)</param>
        /// <param name="startTime">Start times of waivers to fetch. (optional)</param>
        /// <param name="subDescription">Substring matching for description. (optional)</param>
        /// <returns>Waiver</returns>
        Waiver GetWaivers (bool? closed = null, List<string> description = null, List<string> expiration = null, List<string> grantedBy = null, List<string> id = null, List<string> name = null, string pageLimit = null, string pageStart = null, List<string> policyId = null, List<string> policyName = null, List<string> responsible = null, List<string> startTime = null, List<string> subDescription = null);

        /// <summary>
        /// Search waivers (since 1.5)
        /// </summary>
        /// <remarks>
        /// Returns a list of all waivers or only those waivers that match the provided filter criteria.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="closed">Closed condition of waivers to fetch. (optional)</param>
        /// <param name="description">Descriptions of waivers to fetch. (optional)</param>
        /// <param name="expiration">Expiration times of waivers to fetch. (optional)</param>
        /// <param name="grantedBy">Granted by waivers to fetch. (optional)</param>
        /// <param name="id">IDs of waivers to fetch. (optional)</param>
        /// <param name="name">Names of waivers to fetch. (optional)</param>
        /// <param name="pageLimit">Page limit for paging support (optional)</param>
        /// <param name="pageStart">Page start for paging support (optional)</param>
        /// <param name="policyId">Policy IDs of waivers to fetch. (optional)</param>
        /// <param name="policyName">Policy names of waivers to fetch. (optional)</param>
        /// <param name="responsible">Responsibles of waivers to fetch. (optional)</param>
        /// <param name="startTime">Start times of waivers to fetch. (optional)</param>
        /// <param name="subDescription">Substring matching for description. (optional)</param>
        /// <returns>ApiResponse of Waiver</returns>
        ApiResponse<Waiver> GetWaiversWithHttpInfo (bool? closed = null, List<string> description = null, List<string> expiration = null, List<string> grantedBy = null, List<string> id = null, List<string> name = null, string pageLimit = null, string pageStart = null, List<string> policyId = null, List<string> policyName = null, List<string> responsible = null, List<string> startTime = null, List<string> subDescription = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Delete a waiver (since 1.11)
        /// </summary>
        /// <remarks>
        /// Removes a waiver
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rkWaiverId">Id of the waiver</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteWaiverAsync (string rkWaiverId);

        /// <summary>
        /// Delete a waiver (since 1.11)
        /// </summary>
        /// <remarks>
        /// Removes a waiver
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rkWaiverId">Id of the waiver</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteWaiverAsyncWithHttpInfo (string rkWaiverId);
        /// <summary>
        /// Get waiver details by ID. (since 1.5)
        /// </summary>
        /// <remarks>
        /// Returns the details of an individual waiver.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rkWaiverId">ID of Waiver to fetch</param>
        /// <returns>Task of Waiver</returns>
        System.Threading.Tasks.Task<Waiver> GetWaiverByIdAsync (string rkWaiverId);

        /// <summary>
        /// Get waiver details by ID. (since 1.5)
        /// </summary>
        /// <remarks>
        /// Returns the details of an individual waiver.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rkWaiverId">ID of Waiver to fetch</param>
        /// <returns>Task of ApiResponse (Waiver)</returns>
        System.Threading.Tasks.Task<ApiResponse<Waiver>> GetWaiverByIdAsyncWithHttpInfo (string rkWaiverId);
        /// <summary>
        /// Search waivers (since 1.5)
        /// </summary>
        /// <remarks>
        /// Returns a list of all waivers or only those waivers that match the provided filter criteria.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="closed">Closed condition of waivers to fetch. (optional)</param>
        /// <param name="description">Descriptions of waivers to fetch. (optional)</param>
        /// <param name="expiration">Expiration times of waivers to fetch. (optional)</param>
        /// <param name="grantedBy">Granted by waivers to fetch. (optional)</param>
        /// <param name="id">IDs of waivers to fetch. (optional)</param>
        /// <param name="name">Names of waivers to fetch. (optional)</param>
        /// <param name="pageLimit">Page limit for paging support (optional)</param>
        /// <param name="pageStart">Page start for paging support (optional)</param>
        /// <param name="policyId">Policy IDs of waivers to fetch. (optional)</param>
        /// <param name="policyName">Policy names of waivers to fetch. (optional)</param>
        /// <param name="responsible">Responsibles of waivers to fetch. (optional)</param>
        /// <param name="startTime">Start times of waivers to fetch. (optional)</param>
        /// <param name="subDescription">Substring matching for description. (optional)</param>
        /// <returns>Task of Waiver</returns>
        System.Threading.Tasks.Task<Waiver> GetWaiversAsync (bool? closed = null, List<string> description = null, List<string> expiration = null, List<string> grantedBy = null, List<string> id = null, List<string> name = null, string pageLimit = null, string pageStart = null, List<string> policyId = null, List<string> policyName = null, List<string> responsible = null, List<string> startTime = null, List<string> subDescription = null);

        /// <summary>
        /// Search waivers (since 1.5)
        /// </summary>
        /// <remarks>
        /// Returns a list of all waivers or only those waivers that match the provided filter criteria.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="closed">Closed condition of waivers to fetch. (optional)</param>
        /// <param name="description">Descriptions of waivers to fetch. (optional)</param>
        /// <param name="expiration">Expiration times of waivers to fetch. (optional)</param>
        /// <param name="grantedBy">Granted by waivers to fetch. (optional)</param>
        /// <param name="id">IDs of waivers to fetch. (optional)</param>
        /// <param name="name">Names of waivers to fetch. (optional)</param>
        /// <param name="pageLimit">Page limit for paging support (optional)</param>
        /// <param name="pageStart">Page start for paging support (optional)</param>
        /// <param name="policyId">Policy IDs of waivers to fetch. (optional)</param>
        /// <param name="policyName">Policy names of waivers to fetch. (optional)</param>
        /// <param name="responsible">Responsibles of waivers to fetch. (optional)</param>
        /// <param name="startTime">Start times of waivers to fetch. (optional)</param>
        /// <param name="subDescription">Substring matching for description. (optional)</param>
        /// <returns>Task of ApiResponse (Waiver)</returns>
        System.Threading.Tasks.Task<ApiResponse<Waiver>> GetWaiversAsyncWithHttpInfo (bool? closed = null, List<string> description = null, List<string> expiration = null, List<string> grantedBy = null, List<string> id = null, List<string> name = null, string pageLimit = null, string pageStart = null, List<string> policyId = null, List<string> policyName = null, List<string> responsible = null, List<string> startTime = null, List<string> subDescription = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WaiversApi : IWaiversApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WaiversApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WaiversApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WaiversApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public WaiversApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Delete a waiver (since 1.11) Removes a waiver
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rkWaiverId">Id of the waiver</param>
        /// <returns></returns>
        public void DeleteWaiver (string rkWaiverId)
        {
             DeleteWaiverWithHttpInfo(rkWaiverId);
        }

        /// <summary>
        /// Delete a waiver (since 1.11) Removes a waiver
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rkWaiverId">Id of the waiver</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteWaiverWithHttpInfo (string rkWaiverId)
        {
            // verify the required parameter 'rkWaiverId' is set
            if (rkWaiverId == null)
                throw new ApiException(400, "Missing required parameter 'rkWaiverId' when calling WaiversApi->DeleteWaiver");

            var localVarPath = "/waivers/{rkWaiverId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (rkWaiverId != null) localVarPathParams.Add("rkWaiverId", this.Configuration.ApiClient.ParameterToString(rkWaiverId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteWaiver", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Delete a waiver (since 1.11) Removes a waiver
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rkWaiverId">Id of the waiver</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteWaiverAsync (string rkWaiverId)
        {
             await DeleteWaiverAsyncWithHttpInfo(rkWaiverId);

        }

        /// <summary>
        /// Delete a waiver (since 1.11) Removes a waiver
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rkWaiverId">Id of the waiver</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteWaiverAsyncWithHttpInfo (string rkWaiverId)
        {
            // verify the required parameter 'rkWaiverId' is set
            if (rkWaiverId == null)
                throw new ApiException(400, "Missing required parameter 'rkWaiverId' when calling WaiversApi->DeleteWaiver");

            var localVarPath = "/waivers/{rkWaiverId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (rkWaiverId != null) localVarPathParams.Add("rkWaiverId", this.Configuration.ApiClient.ParameterToString(rkWaiverId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteWaiver", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Get waiver details by ID. (since 1.5) Returns the details of an individual waiver.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rkWaiverId">ID of Waiver to fetch</param>
        /// <returns>Waiver</returns>
        public Waiver GetWaiverById (string rkWaiverId)
        {
             ApiResponse<Waiver> localVarResponse = GetWaiverByIdWithHttpInfo(rkWaiverId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get waiver details by ID. (since 1.5) Returns the details of an individual waiver.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rkWaiverId">ID of Waiver to fetch</param>
        /// <returns>ApiResponse of Waiver</returns>
        public ApiResponse< Waiver > GetWaiverByIdWithHttpInfo (string rkWaiverId)
        {
            // verify the required parameter 'rkWaiverId' is set
            if (rkWaiverId == null)
                throw new ApiException(400, "Missing required parameter 'rkWaiverId' when calling WaiversApi->GetWaiverById");

            var localVarPath = "/waivers/{rkWaiverId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (rkWaiverId != null) localVarPathParams.Add("rkWaiverId", this.Configuration.ApiClient.ParameterToString(rkWaiverId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetWaiverById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Waiver>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Waiver) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Waiver)));
        }

        /// <summary>
        /// Get waiver details by ID. (since 1.5) Returns the details of an individual waiver.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rkWaiverId">ID of Waiver to fetch</param>
        /// <returns>Task of Waiver</returns>
        public async System.Threading.Tasks.Task<Waiver> GetWaiverByIdAsync (string rkWaiverId)
        {
             ApiResponse<Waiver> localVarResponse = await GetWaiverByIdAsyncWithHttpInfo(rkWaiverId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get waiver details by ID. (since 1.5) Returns the details of an individual waiver.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rkWaiverId">ID of Waiver to fetch</param>
        /// <returns>Task of ApiResponse (Waiver)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Waiver>> GetWaiverByIdAsyncWithHttpInfo (string rkWaiverId)
        {
            // verify the required parameter 'rkWaiverId' is set
            if (rkWaiverId == null)
                throw new ApiException(400, "Missing required parameter 'rkWaiverId' when calling WaiversApi->GetWaiverById");

            var localVarPath = "/waivers/{rkWaiverId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (rkWaiverId != null) localVarPathParams.Add("rkWaiverId", this.Configuration.ApiClient.ParameterToString(rkWaiverId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetWaiverById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Waiver>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Waiver) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Waiver)));
        }

        /// <summary>
        /// Search waivers (since 1.5) Returns a list of all waivers or only those waivers that match the provided filter criteria.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="closed">Closed condition of waivers to fetch. (optional)</param>
        /// <param name="description">Descriptions of waivers to fetch. (optional)</param>
        /// <param name="expiration">Expiration times of waivers to fetch. (optional)</param>
        /// <param name="grantedBy">Granted by waivers to fetch. (optional)</param>
        /// <param name="id">IDs of waivers to fetch. (optional)</param>
        /// <param name="name">Names of waivers to fetch. (optional)</param>
        /// <param name="pageLimit">Page limit for paging support (optional)</param>
        /// <param name="pageStart">Page start for paging support (optional)</param>
        /// <param name="policyId">Policy IDs of waivers to fetch. (optional)</param>
        /// <param name="policyName">Policy names of waivers to fetch. (optional)</param>
        /// <param name="responsible">Responsibles of waivers to fetch. (optional)</param>
        /// <param name="startTime">Start times of waivers to fetch. (optional)</param>
        /// <param name="subDescription">Substring matching for description. (optional)</param>
        /// <returns>Waiver</returns>
        public Waiver GetWaivers (bool? closed = null, List<string> description = null, List<string> expiration = null, List<string> grantedBy = null, List<string> id = null, List<string> name = null, string pageLimit = null, string pageStart = null, List<string> policyId = null, List<string> policyName = null, List<string> responsible = null, List<string> startTime = null, List<string> subDescription = null)
        {
             ApiResponse<Waiver> localVarResponse = GetWaiversWithHttpInfo(closed, description, expiration, grantedBy, id, name, pageLimit, pageStart, policyId, policyName, responsible, startTime, subDescription);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Search waivers (since 1.5) Returns a list of all waivers or only those waivers that match the provided filter criteria.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="closed">Closed condition of waivers to fetch. (optional)</param>
        /// <param name="description">Descriptions of waivers to fetch. (optional)</param>
        /// <param name="expiration">Expiration times of waivers to fetch. (optional)</param>
        /// <param name="grantedBy">Granted by waivers to fetch. (optional)</param>
        /// <param name="id">IDs of waivers to fetch. (optional)</param>
        /// <param name="name">Names of waivers to fetch. (optional)</param>
        /// <param name="pageLimit">Page limit for paging support (optional)</param>
        /// <param name="pageStart">Page start for paging support (optional)</param>
        /// <param name="policyId">Policy IDs of waivers to fetch. (optional)</param>
        /// <param name="policyName">Policy names of waivers to fetch. (optional)</param>
        /// <param name="responsible">Responsibles of waivers to fetch. (optional)</param>
        /// <param name="startTime">Start times of waivers to fetch. (optional)</param>
        /// <param name="subDescription">Substring matching for description. (optional)</param>
        /// <returns>ApiResponse of Waiver</returns>
        public ApiResponse< Waiver > GetWaiversWithHttpInfo (bool? closed = null, List<string> description = null, List<string> expiration = null, List<string> grantedBy = null, List<string> id = null, List<string> name = null, string pageLimit = null, string pageStart = null, List<string> policyId = null, List<string> policyName = null, List<string> responsible = null, List<string> startTime = null, List<string> subDescription = null)
        {

            var localVarPath = "/waivers";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (closed != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "closed", closed)); // query parameter
            if (description != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "description", description)); // query parameter
            if (expiration != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "expiration", expiration)); // query parameter
            if (grantedBy != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "grantedBy", grantedBy)); // query parameter
            if (id != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "id", id)); // query parameter
            if (name != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "name", name)); // query parameter
            if (pageLimit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "pageLimit", pageLimit)); // query parameter
            if (pageStart != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "pageStart", pageStart)); // query parameter
            if (policyId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "policyId", policyId)); // query parameter
            if (policyName != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "policyName", policyName)); // query parameter
            if (responsible != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "responsible", responsible)); // query parameter
            if (startTime != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "startTime", startTime)); // query parameter
            if (subDescription != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "sub_description", subDescription)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetWaivers", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Waiver>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Waiver) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Waiver)));
        }

        /// <summary>
        /// Search waivers (since 1.5) Returns a list of all waivers or only those waivers that match the provided filter criteria.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="closed">Closed condition of waivers to fetch. (optional)</param>
        /// <param name="description">Descriptions of waivers to fetch. (optional)</param>
        /// <param name="expiration">Expiration times of waivers to fetch. (optional)</param>
        /// <param name="grantedBy">Granted by waivers to fetch. (optional)</param>
        /// <param name="id">IDs of waivers to fetch. (optional)</param>
        /// <param name="name">Names of waivers to fetch. (optional)</param>
        /// <param name="pageLimit">Page limit for paging support (optional)</param>
        /// <param name="pageStart">Page start for paging support (optional)</param>
        /// <param name="policyId">Policy IDs of waivers to fetch. (optional)</param>
        /// <param name="policyName">Policy names of waivers to fetch. (optional)</param>
        /// <param name="responsible">Responsibles of waivers to fetch. (optional)</param>
        /// <param name="startTime">Start times of waivers to fetch. (optional)</param>
        /// <param name="subDescription">Substring matching for description. (optional)</param>
        /// <returns>Task of Waiver</returns>
        public async System.Threading.Tasks.Task<Waiver> GetWaiversAsync (bool? closed = null, List<string> description = null, List<string> expiration = null, List<string> grantedBy = null, List<string> id = null, List<string> name = null, string pageLimit = null, string pageStart = null, List<string> policyId = null, List<string> policyName = null, List<string> responsible = null, List<string> startTime = null, List<string> subDescription = null)
        {
             ApiResponse<Waiver> localVarResponse = await GetWaiversAsyncWithHttpInfo(closed, description, expiration, grantedBy, id, name, pageLimit, pageStart, policyId, policyName, responsible, startTime, subDescription);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Search waivers (since 1.5) Returns a list of all waivers or only those waivers that match the provided filter criteria.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="closed">Closed condition of waivers to fetch. (optional)</param>
        /// <param name="description">Descriptions of waivers to fetch. (optional)</param>
        /// <param name="expiration">Expiration times of waivers to fetch. (optional)</param>
        /// <param name="grantedBy">Granted by waivers to fetch. (optional)</param>
        /// <param name="id">IDs of waivers to fetch. (optional)</param>
        /// <param name="name">Names of waivers to fetch. (optional)</param>
        /// <param name="pageLimit">Page limit for paging support (optional)</param>
        /// <param name="pageStart">Page start for paging support (optional)</param>
        /// <param name="policyId">Policy IDs of waivers to fetch. (optional)</param>
        /// <param name="policyName">Policy names of waivers to fetch. (optional)</param>
        /// <param name="responsible">Responsibles of waivers to fetch. (optional)</param>
        /// <param name="startTime">Start times of waivers to fetch. (optional)</param>
        /// <param name="subDescription">Substring matching for description. (optional)</param>
        /// <returns>Task of ApiResponse (Waiver)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Waiver>> GetWaiversAsyncWithHttpInfo (bool? closed = null, List<string> description = null, List<string> expiration = null, List<string> grantedBy = null, List<string> id = null, List<string> name = null, string pageLimit = null, string pageStart = null, List<string> policyId = null, List<string> policyName = null, List<string> responsible = null, List<string> startTime = null, List<string> subDescription = null)
        {

            var localVarPath = "/waivers";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (closed != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "closed", closed)); // query parameter
            if (description != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "description", description)); // query parameter
            if (expiration != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "expiration", expiration)); // query parameter
            if (grantedBy != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "grantedBy", grantedBy)); // query parameter
            if (id != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "id", id)); // query parameter
            if (name != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "name", name)); // query parameter
            if (pageLimit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "pageLimit", pageLimit)); // query parameter
            if (pageStart != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "pageStart", pageStart)); // query parameter
            if (policyId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "policyId", policyId)); // query parameter
            if (policyName != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "policyName", policyName)); // query parameter
            if (responsible != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "responsible", responsible)); // query parameter
            if (startTime != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "startTime", startTime)); // query parameter
            if (subDescription != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "sub_description", subDescription)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetWaivers", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Waiver>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Waiver) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Waiver)));
        }

    }
}
